// Generated by LiveScript 1.4.0
(function(){
  var morgan, dateformat, fs, data, format, path, logger;
  morgan = require('morgan');
  dateformat = require('dateformat');
  fs = require('fs');
  data = require('./data');
  format = '[:date] :visitor 網址：:url 狀態：:status 回應時間：:response-time ms';
  path = './data.json';
  morgan.token('visitor', function(req, res){
    var write;
    data.count++;
    write = {
      count: data.count
    };
    fs.writeFile(path, JSON.stringify(write, null, 4), function(err){
      if (err) {
        return console.log('[*] 錯誤！無法寫入 json');
      }
    });
    return data.count;
  });
  logger = morgan(format, {
    skip: function(req, res){
      return res.statusCode == 404;
    }
  });
  exports.logger = logger;
}).call(this);
